# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TUIVoiceRoomApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TXAppBasic', :path => "TXAppBasic/"
  pod 'TXLiteAVSDK_TRTC_Preview', :podspec => 'https://liteav.sdk.qcloud.com/pod/liteavsdkspec/TXLiteAVSDK_TRTC_Preview.podspec'
  pod 'TUIVoiceRoom', :path => "./", :subspecs => ["TRTC_Preview"]
end
